# 绘制红灯绿灯
import turtle
light = turtle.Turtle()
light.hideturtle()
light.color("red", "red")
light.begin_fill()
light.circle(20)
light.end_fill()
light.penup()
light.goto(0,-60)
light.pendown()
light.color("green", "green")
light.begin_fill()
light.circle(20)
light.end_fill()