# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GitHub\练习\ui\pyqt\Weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(511, 446)
        self.queryButton = QtWidgets.QPushButton(Dialog)
        self.queryButton.setGeometry(QtCore.QRect(80, 360, 93, 28))
        self.queryButton.setObjectName("queryButton")
        self.clear0Button = QtWidgets.QPushButton(Dialog)
        self.clear0Button.setGeometry(QtCore.QRect(270, 360, 93, 28))
        self.clear0Button.setObjectName("clear0Button")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 481, 341))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 40, 72, 20))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(230, 40, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 70, 451, 241))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        self.queryButton.clicked.connect(Dialog.queryWeather)
        self.clear0Button.clicked.connect(Dialog.clearText)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.queryButton.setText(_translate("Dialog", "查询"))
        self.clear0Button.setText(_translate("Dialog", "清除"))
        self.groupBox.setTitle(_translate("Dialog", "天气查询"))
        self.label.setText(_translate("Dialog", "城市"))
        self.comboBox.setItemText(0, _translate("Dialog", "北京"))
        self.comboBox.setItemText(1, _translate("Dialog", "天津"))
        self.comboBox.setItemText(2, _translate("Dialog", "上海"))
